on: [push]

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  pages:
    needs: build
    if: ${{ success() && github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/pages.yml
  draft-release:
    needs: build
    if: ${{ success() && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "build"
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            Main.html
            Main.min.js
